// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kogxvvtfdgugwroszkfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvZ3h2dnRmZGd1Z3dyb3N6a2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDgxNjYsImV4cCI6MjA2Mjk4NDE2Nn0.Hszb3uZbX9-ipcTMbhVXFnGpN01IOPOg-JDHQWRlam8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);